### ISSUE TITLE
when value is supposed to be an empty arrayref

### ISSUE THREAD

**Issue by mickeyn** [miyagawa/Hash-MultiValue#11]
Hi,

I have the following issue with decoded data (JSON) used to create a HMV -
in case the value is an empty JSON array, it's treated as an empty list of values and I can't retrieve it back as an arrayref.

Here's a code example:                                                                                                               

``` perl
use strict;
use warnings;
use Hash::MultiValue;
use JSON::XS qw< decode_json >;

my $incoming = q({"data":[]});  # valid JSON
my $decoded = decode_json($incoming); # { data => [] }
Hash::MultiValue->from_mixed( %{$decoded} )->get("data"); # undef
```

I understand why this happens, but what would you recommend doing in this case to retain the original passed value? (I know [[]] works, but that will require messing with the decoded request data)

**Comment by ap** [comment]
I would probably recommend using something other than HMV. Depends on the rest of your code.

The `get_all` in your example is not returning `undef` but an empty list. That’s the whole point of HMV: you always get a list from `get_all`, and you always get a single value from `get`. It was designed this way so that you won’t need to constantly check types (like you have to with Catalyst’s `parameters` interface) or constantly keep context in mind (like with CGI’s `param` interface).

So you give it an empty array, then you ask it what values were in the array. Of course the answer is none. You can’t get a different answer with that input. Maybe you can do something like

``` perl
$decoded->{'__keys__'} = { map $_ => 1, keys %$decoded };
```

before creating the HMV object, so you can later look at `$hmv->{'__keys__'}{'data'}` for the answer you need. If that’s already too much messing with the input, then you have the wrong tool.

**Comment by mickeyn** [comment]
note: I edited the example to use 'get' - that does return undef.

**Comment by miyagawa** [comment]
@mickeyn because you're getting the object from JSON, which has an unambiguous semantics for the value types, there's no point of using Hash::MultiValue's `from_mixed`. Just use `new` and it will retain the original value.

**Comment by mickeyn** [comment]
cool, that works :)

@miyagawa :+1:

**Comment by xsawyerx** [comment]
The problem described here, I think, is a bit more nuanced.

When you use `HMV`, having a `null` value for a key is just fine. It will save it as `undef`. If that value is explicitly empty, though, it will ignore it. These are two cases that aren't even "it's an empty list in and of itself", which should also be accounted for.

Considering `HMV` supports `null` -> `undef` conversion, it seems like it's basically "I do accept this, but not those", and that should be addressed - one way or the other, IMHO.

**Comment by miyagawa** [comment]
Yeah, the fundamental question is that why would you want to pass JSON values, which has  unambiguous semantics about its values, to something like Hash::MultiValue.

H::MV is there because with traditional framework, when you pass a query such as `?a=1&b=1&b=2` you'll get params like `{ a => 1, b => [ 1, 2 ] }` so you'll get different type of values depending on user inputs, which could easily be a security hole in your app (think: `User->find($id)` and you'll pass `?id=1&id=2`, which some ORM could very well translate it into an OR query). There's also a `param()` method that would return a scalar or list depending on contexts, which would lead to a similar problem.

The problem doesn't really go away with JSON though. If you feed it into Hash::MultiValue, an array ref becomes multi value options, but if you really want to pass array ref as a single value, you could make it a double reference, as originally suggested in the first post.

That means, even if you use Hash::MultiValue, as long as you allow JSON post, the user input could inject whatever type of data to your request, so you have to validate the input data type more strictly than regular form post. It is often called "JSON parameter/SQL injection" and you can search for them to find some security vulnerabilities.

I would strongly discourage using JSON to automatically populate request parameters, because its fundamenrally different from regular www-form-urlencoded based POST, and roll your own JSON schema based validator, if required, to restrict the data type you can send.

**Comment by ap** [comment]
> The problem described here, I think, is a bit more nuanced.
> 
> When you use HMV, having a `null` value for a key is just fine. It will save it as `undef`.

When you _decode JSON_, `null`s become `undef`. HMV has nothing to do with that, it is just a hash with multiple values per key.

> If that value is explicitly empty, though, it will ignore it. These are two cases that aren't even "it's an empty list in and of itself", which should also be accounted for.
> 
> Considering HMV supports `null` -> `undef` conversion, it seems like it's basically "I do accept this, but not those", and that should be addressed - one way or the other, IMHO.

Perl hashes have a simple distinction between `exists $foo{bar}` and `defined $foo{bar}`: a hash key can exist but its value is `undef`. And HMV gives you the same semantics as normal hashes if you do `exists $hmv->{bar}` vs `defined $hmv->{bar}`.

But HMV keys can have multiple values that you can retrieve with `get_all`. (So you can even have _multiple_ undef values for a single key.) Now you are saying that unlike normal hashes, HMV should have an additional distinction where a key doesn’t have any values (not even a single `undef`) but still “exists”. So what should `exists $hmv->{bar}` say for such a key? It can’t say true, because then you will treat a key with a single value that’s `undef` the same as a key without any values at all. But it can’t say false either because then you might miss a key that exists without existing (which is some kind of Lovecraftian spookiness). So either way `exists` must have non-obvious gotcha edge cases. For what gain?

Not the ability to handle JSON.

In JSON, keys _never_ have multiple values, they _always_ have a single value. It’s just that single value can be a container. So the JSON data model makes a distinction between a key that has a single plain value and a key that has a single value wrapped in an array. And of course a container can be empty, but that doesn’t matter to the key, the key still exists and has one value – “exists” and “has one value” are the exact same thing.

HMV hashes can store multiple values per key, each of which can be a container – which is wasted on JSON, because JSON never does have multiple values per key.

OTOH the _whole point_ of `from_mixed` is to _erase_ the distinction between a single plain value and the same value wrapped in an array, because it was designed to convert the representation of yet another data model which _doesn’t have_ this distinction: query strings, which are hashes with multiple values per key – but only simple values, not containers. Someone once came up with the idea of representing these multi-plain-valued hashes using Perl hashes by wrapping multiple values in arrays but leaving single values as plain values. It was then discovered that this representation is not convenient because you have to constantly check the type of the value. So HMV was designed to allow multiple values per key _and_ to allow you to say whether you want one value or all values, so that you can write code that always gets what it expected. And `from_mixed` and `mixed` were added to make it easy to convert with the inconvenient representation.

So, to recap the data models:
- query string/`from_mixed`: multiple values per key, but no container values
- Perl hash: single value per key, which may be a container
- HMV: multiple values per key, which may be containers
- JSON: single value per key, which may be a container

Now which of these data models best matches JSON?

You can also see here why @miyagawa’s suggestion works: if you never store multiple values into each key then HMV is indistinguishable from a Perl hash.

(Actually the data models are a bit more complicated than that, because both query strings and HMV have ordered keys. Perl hashes and JSON do not. Again Perl hashes and JSON have the exact same semantics. And again HMV semantics are a superset of everything. (In fact, even though query strings have ordered keys, `from_mixed` does not, so these data models are actually different.))

**Comment by ap** [comment]
> I would strongly discourage using JSON to automatically populate request parameters, because its fundamenrally different from regular www-form-urlencoded based POST, and roll your own JSON schema based validator, if required, to restrict the data type you can send.

Agree. Hmm, so if JSON input should always be validated… sounds like a job for a framework to provide affordances to make that easy? :smile:

**Comment by xsawyerx** [comment]
I appreciate the exhaustive answers you provided and I retract my comments. Thank you.
